### ISSUE TITLE
FR: Allow automatic helper registration

### ISSUE THREAD

**Issue by lesaff** [justonestep/processwire-twigextensions#10]
@justb3a, here's a challenge for you. Wouldn't it be nice to allow automatic registration of helpers and extensions (by way of auto-loading classes using PSR-4)?

This way, anyone can add their own custom filters/helpers to this module without asking for a PR.

What do you think?

**Comment by justb3a** [comment]
Sure this would be nice, but I think this would be a kind of *"overengineering"*. PR's just work fine for this purpose and unfortunately I currently don't have the time to *"play around"* and add something like this. **But** feel free to send a PR which adds this feature ;)
