### ISSUE TITLE
Provide options to enable the text extensions

### ISSUE THREAD

**Issue by gmclelland** [justonestep/processwire-twigextensions#2]
I'm trying to use the truncate filter in https://github.com/twigphp/Twig-extensions, but I'm not sure how.

Can you provide an option in this module to enable the text extensions?

**Comment by gmclelland** [comment]
I modified the module to add this option.  Would you like me to create a pull request?

**Comment by justb3a** [comment]
yeah, sure!

**Comment by gmclelland** [comment]
There you go https://github.com/justb3a/processwire-twigextensions/pull/3
