### ISSUE TITLE
Debug throws exeption if ProcessWires $config->debug is false

### ISSUE THREAD

**Issue by jmartsch** [justonestep/processwire-twigextensions#4]
Exception: Unknown "dump" function is thrown, when $config->debug is false.
If $config->debug is false the twig debug messages should just be omitted.

**Comment by justb3a** [comment]
Initially I added the extension only if debug mode was turned on. That leads to an exception if the debug mode was turned off and a `{{dump()}}` statement still existed. I fixed it by including the extension independent from whether debug mode is turned on or not. So now if debug mode is durned off, the statement is just omitted.
