### ISSUE TITLE
Getting module not installable error on 3.0.59

### ISSUE THREAD

**Issue by lesaff** [justonestep/processwire-twigextensions#6]
I already have both dependencies met (installed) but still getting this error. I am running 3.0.59

<img width="580" alt="screen shot 2017-04-14 at 8 51 13 pm" src="https://cloud.githubusercontent.com/assets/1151181/25058839/4671f4fe-2154-11e7-9222-62f6db798e94.png">

**Comment by justb3a** [comment]
Hi,
if you have the following modules installed, you should be able to install this module.

- TemplateEngineFactory
- TemplateEngineTwig

Did you try to refresh the module cache (Admin > Modules > Refresh)?

**Comment by lesaff** [comment]
I think it was a one-off issue. I am closing this, sorry to bother you.
